# Copyright 2023 Antrea Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM antrea/antrea-ubuntu:latest@sha256:2c529f71d486f972b3aa59c0e290403a57f0719138be2fa0d9b66626565f9e50

LABEL maintainer="Antrea <projectantrea-dev@googlegroups.com>"
LABEL description="Test image"

COPY VERSION /VERSION
