# Copyright 2023 Antrea Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM antrea/antrea-ubuntu:latest@sha256:30b57dd217240d140559ce3d86a116438fd5285b1df71493cb34ec20de09332f

LABEL maintainer="Antrea <projectantrea-dev@googlegroups.com>"
LABEL description="Test image"

COPY VERSION /VERSION
